### ISSUE TITLE
Reproduce estExecCost negative bug encountered 

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato-network#145]
During the malicious provider test flow,  I saw that buidler's console.log spat out a negative number for `_processProviderPayables` `estGasConsumed`.

I then added SafeMath to this calc in d755b1f1d2edc6c5403f3d40056907864a714e12 #131 
```solidity
uint256 estGasConsumed = (EXEC_TX_OVERHEAD + estExecTxGas).sub(
    gasleft(),
    "GelatoCore._processProviderPayables: estGasConsumed underflow"
);
```

To reproduce, I think we need to run the scenario where the MockActionMaliciousProvider fails.

**Comment by hilmarx** [comment]
closed @gitpusha
